# Generated by Django 4.2.3 on 2023-07-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ctegory',
            new_name='Category',
        ),
    ]
