# Generated by Django 4.2.3 on 2023-07-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
