# Generated by Django 4.2.3 on 2023-08-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_nomer',
            new_name='phone_number',
        ),
    ]
