# Generated by Django 4.2.3 on 2023-08-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_phone_nomer_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptions',
            new_name='description',
        ),
    ]
