# Generated by Django 4.2.3 on 2023-08-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_descriptions_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
    ]
