# Generated by Django 4.0.6 on 2023-08-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_merge_0003_auto_20210726_1109_0003_auto_20210727_0940'),
        ('food', '0004_remove_product_cost'),
    ]

    operations = [
    ]
